spring:
  application:
    name: auth-service
  cloud:
    discovery:
      enabled: true
      settings:
        web-allow-others: true

eureka:
  client:
    serviceUrl:
      defaultZone:  http://discovery:8761/eureka/
  instance:
    preferIpAddress: true

server:
  port: 9001