apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-app
  labels:
    app: account-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-app
  template:
    metadata:
      labels:
        app: auth-service-app
    spec:
      containers:
        - name: auth-service-app
          image: europe-west1-docker.pkg.dev/ebank-428423/ebank-docker-repo/auth-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9080

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-svc
spec:
  ports:
    - targetPort: 9080
      port: 80
  selector:
    app: auth-service-app