apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-cm
data:
  eureka_service_address: http://discovery:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: discovery
  labels:
    app: discovery
spec:
  selector:
    app: discovery
  type: NodePort
  ports:
    - port: 80
      targetPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: discovery
  labels:
    app: discovery
spec:
  clusterIP: None
  ports:
    - port: 8761
      name: discovery
  selector:
    app: discovery
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery
spec:
  serviceName: "discovery"
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - name: discovery
          image: froukabidock/discovery:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: discovery
              valueFrom:
                configMapKeyRef:
                  name: discovery-cm
                  key: discovery_service_address