apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
  labels:
    app: user-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
        - name: user-service-app
          image: europe-west1-docker.pkg.dev/ebank-428423/ebank-docker-repo/user:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9040

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
spec:
  ports:
    - targetPort: 9040
      port: 80
  selector:
    app: user-service-app